spring:
  cache:
    type: redis
    redis:
      time-to-live: 5000
      cache-null-values: false
      host: k8a7071.p.ssafy.io
      port: 3309
      password: 'eodrms1111!'
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: http://13.125.215.143:9092, http://54.180.139.100:9092, http://54.180.165.36:9092
    consumer:
      group-id: grade_sign_group
      auto-offset-reset: latest
      bootstrap-servers: http://13.125.215.143:9092, http://54.180.139.100:9092, http://54.180.165.36:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            add:
              type:
                headers: 'false'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false #To beautify or pretty print the SQL
        show_sql: false #show sql
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k8a7071.p.ssafy.io:3308/luckquiz?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: carrot707
    password: ekdrmsehdrms1111!!
  cloud:
    gcp:
      storage:
        bucket: luckquiz
        project-id: snappy-analog-384101
        credentials:
          location: classpath:snappy-analog-384101-5ff843401827.json
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-http-form-post-size: 3MB
  port: 8081